version: '3.8'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=password123!
      - MYSQL_DATABASE=hockshi
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306


#terminal cmd
#docker run -p 3306:3306 -d --name mariadb -e MYSQL_DATABASE=hockshi -e MARIADB_ROOT_PASSWORD=Password123! mariadb

     